# Generated by Django 3.2.9 on 2021-12-04 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='accident_number',
            field=models.CharField(max_length=25, unique=True, verbose_name='номер постановления'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='fines.car', verbose_name='автомобиль'),
        ),
    ]
