# Generated by Django 3.2.9 on 2021-12-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0002_auto_20211204_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='accident_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата нарушения'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='fine_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата вынесения постановления'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='сумма штрафа'),
        ),
    ]
