# Generated by Django 3.2.9 on 2021-12-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0003_auto_20211204_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='accident_date_time',
        ),
        migrations.AddField(
            model_name='fine',
            name='accident_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата нарушения'),
        ),
    ]
