# Generated by Django 3.2.9 on 2021-12-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0004_auto_20211204_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='accident_time',
            field=models.TimeField(blank=True, null=True, verbose_name='время нарушения'),
        ),
    ]
