# Generated by Django 3.2.9 on 2021-12-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0007_fine_pay_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='excel файл')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
