# Generated by Django 3.2.9 on 2021-12-26 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0008_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'отчет', 'verbose_name_plural': 'отчеты'},
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(upload_to='media', verbose_name='excel файл'),
        ),
        migrations.CreateModel(
            name='DriverOnCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.DateTimeField(verbose_name='время получения авто')),
                ('end_time', models.DateTimeField(verbose_name='время сдачи авто')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fines.car', verbose_name='автомобиль')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fines.driver', verbose_name='водитель')),
            ],
            options={
                'verbose_name': 'учет времени за рулем',
                'verbose_name_plural': 'учет времени за рулем',
            },
        ),
    ]
