# Generated by Django 3.2.9 on 2021-12-26 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0009_auto_20211226_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='accident_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время нарушения'),
        ),
        migrations.AddField(
            model_name='fine',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fines.driver', verbose_name='водитель'),
        ),
    ]
