# Generated by Django 3.2.9 on 2021-12-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0010_auto_20211226_1903'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driveroncar',
            unique_together={('driver', 'car', 'begin_time', 'end_time')},
        ),
    ]
